Clean up extension and add Services.yaml
b13/newspage pull request #9
Opened 2022-12-01 09:39 UTC by jschlier

2022-12-01 12:22 UTC, ervaude requested changes

2022-12-01 12:22 UTC, ervaude commented on Classes/Event/CreatingPaginationEvent.php
> +    private PaginationInterface $pagination;
Please set initial value to `null` as this is not initialized in the constructor.

```
private ?PaginationInterface $pagination = null;
```

2022-12-01 12:22 UTC, ervaude commented on Classes/Event/CreatingPaginationEvent.php
> +    public function getPagination(): PaginationInterface
Could also return `null` if Pagination was not set yet.

2022-12-01 12:22 UTC, ervaude commented on Classes/Event/CreatingPaginationEvent.php
> +        return isset($this->pagination);
Check for $this->pagination instanceof PaginationInterface

2022-12-01 12:22 UTC, ervaude commented on ext_localconf.php
> +    if (version_compare(TYPO3_version, '11.0.0', '<')) {
Please use `\TYPO3\CMS\Core\Information\Typo3Version`for this

2022-12-23 19:04 UTC, jschlier commented
I included your suggestions @ervaude and also caught the pagination being null in the controller. Shouldn't happen, but the eventl istener _could_ be unset by configuration ?

Much better. Thanks!

2023-05-26 09:35 UTC, merged